import * as fs from 'fs';
import * as path from 'path';

import {
	identifier,
	list,
	destructure,
} from './src/patterns/index.js';
import * as Pattern from './src/patterns/index.js';
import {DELIMS} from './src/selectors.js';



await fs.promises.writeFile(path.join(path.dirname(new URL(import.meta.url).pathname), 'syntaxes', 'cp.tmLanguage.json'), JSON.stringify({
	$schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
	name: 'Counterpoint',
	scopeName: 'source.cp',
	repository: {
		Arguments:                     Pattern.ARGUMENTS,
		Block:                         Pattern.BLOCK,
		Captures:                      list('meta.captures.cp', DELIMS.CAPTURES[0], DELIMS.CAPTURES[1], [{include: '#ModifiersDeclarationLet'}, identifier()]),
		ClassBody:                     Pattern.CLASS_BODY,
		CommentBlock:                  Pattern.COMMENT_BLOCK,
		CommentLine:                   Pattern.COMMENT_LINE,
		ConstructorField:              Pattern.CONSTRUCTOR_FIELD,
		ConstructorParameters:         list('meta.parameters.cp', DELIMS.PARAMS_FN[0], DELIMS.PARAMS_FN[1], [{include: '#ConstructorField'}, {include: '#ParameterPatterns'}]),
		Declaration:                   Pattern.DECLARATION,
		DeclarationClaim:              Pattern.DECLARATION__CLAIM,
		DeclarationClass:              Pattern.DECLARATION__CLASS,
		DeclarationFunction:           Pattern.DECLARATION__FUNCTION,
		DeclarationInterface:          Pattern.DECLARATION__INTERFACE,
		DeclarationLet:                Pattern.DECLARATION__LET,
		DeclarationSet:                Pattern.DECLARATION__SET,
		DeclarationType:               Pattern.DECLARATION__TYPE,
		DeclarationTypefunc:           Pattern.DECLARATION__TYPEFUNC,
		DestructureArgument:           destructure('Argument',         {include: '#IdentifierParameter'}),
		DestructureAssignment:         destructure('Assignment',       {include: '#ExpressionAssignee'}),
		DestructureGenericArgument:    destructure('GenericArgument',  {include: '#IdentifierParameter'}),
		DestructureGenericParameter:   destructure('GenericParameter', {include: '#IdentifierParameter'}),
		DestructureParameter:          destructure('Parameter',        {include: '#IdentifierParameter'}),
		DestructureProperty:           destructure('Property',         {include: '#IdentifierProperty'}),
		DestructureTypeAlias:          destructure('TypeAlias',        {include: '#IdentifierType'}),
		DestructureTypeProperty:       destructure('TypeProperty',     {include: '#IdentifierProperty'}),
		DestructureVariable:           destructure('Variable',         {include: '#IdentifierVariable'}),
		Expression:                    Pattern.EXPRESSION,
		ExpressionAccess:              Pattern.EXPRESSION__ACCESS,
		ExpressionAssignee:            Pattern.EXPRESSION__ASSIGNEE,
		ExpressionCall:                Pattern.EXPRESSION__CALL,
		ExpressionClaim:               Pattern.EXPRESSION__CLAIM,
		ExpressionClass:               Pattern.EXPRESSION__CLASS,
		ExpressionFunction:            Pattern.EXPRESSION__FUNCTION,
		ExpressionStructureGrouping:   Pattern.EXPRESSION__STRUCTURE__GROUPING,
		ExpressionStructureList:       Pattern.EXPRESSION__STRUCTURE__LIST,
		ExpressionStructureSet:        Pattern.EXPRESSION__STRUCTURE__SET,
		ExpressionStructureBlock:      Pattern.EXPRESSION__STRUCTURE__BLOCK,
		GenericArguments:              Pattern.GENERIC_ARGUMENTS,
		GenericParameterPatterns:      Pattern.GENERIC_PARAMETER_PATTERNS,
		GenericParameters:             list('meta.genericparameters.cp', DELIMS.PARAMS_GN[0], DELIMS.PARAMS_GN[1], [{include: '#GenericParameterPatterns'}]),
		Heritage:                      Pattern.HERITAGE,
		IdentifierClass:               identifier('entity.name.class', true),
		IdentifierFunction:            identifier('entity.name.function', true),
		IdentifierParameter:           identifier('variable.parameter', true),
		IdentifierProperty:            identifier('entity.name.method', true),
		IdentifierType:                identifier('entity.name.type', true),
		IdentifierVariable:            identifier('entity.name.variable', true),
		MemberConstructor:             Pattern.MEMBER__CONSTRUCTOR,
		MemberConstructorgroup:        Pattern.MEMBER__CONSTRUCTORGROUP,
		MemberField:                   Pattern.MEMBER__FIELD,
		MemberMethod:                  Pattern.MEMBER__METHOD,
		MemberMethodgroup:             Pattern.MEMBER__METHODGROUP,
		ModifiersDeclarationLet:       Pattern.MODIFIERS__DECLARATION__LET,
		ModifiersDeclarationType:      Pattern.MODIFIERS__DECLARATION__TYPE,
		ModifiersGenericParameter:     Pattern.MODIFIERS__GENERIC_PARAMETER,
		ModifiersParameter:            Pattern.MODIFIERS__PARAMETER,
		Number:                        Pattern.NUMBER,
		ParameterPatterns:             Pattern.PARAMETER_PATTERNS,
		Parameters:                    list('meta.parameters.cp', DELIMS.PARAMS_FN[0], DELIMS.PARAMS_FN[1], [{include: '#ParameterPatterns'}]),
		PossibleGenericParameter:      Pattern.POSSIBLE_GENERIC_PARAMETER,
		PossibleParameter:             Pattern.POSSIBLE_PARAMETER,
		PossibleTypeParameter:         Pattern.POSSIBLE_TYPE_PARAMETER,
		Statement:                     Pattern.STATEMENT,
		StatementControl:              Pattern.STATEMENT__CONTROL,
		StatementControlConditional:   Pattern.STATEMENT__CONTROL__CONDITIONAL,
		StatementExport:               Pattern.STATEMENT__EXPORT,
		StatementImport:               Pattern.STATEMENT__IMPORT,
		String:                        Pattern.STRING,
		Template:                      Pattern.TEMPLATE,
		Type:                          Pattern.TYPE,
		TypeAccess:                    Pattern.TYPE__ACCESS,
		TypeCall:                      Pattern.TYPE_CALL,
		TypeFunction:                  Pattern.TYPE__FUNCTION,
		TypeInterface:                 Pattern.TYPE__INTERFACE,
		TypeParameterPatterns:         Pattern.TYPE_PARAMETER_PATTERNS,
		TypeParameters:                list('meta.parameters.cp', DELIMS.PARAMS_FN[0], DELIMS.PARAMS_FN[1], [{include: '#TypeParameterPatterns'}]),
		TypeStructureGrouping:         Pattern.TYPE__STRUCTURE__GROUPING,
		TypeStructureList:             Pattern.TYPE__STRUCTURE__LIST,
		TypeStructureSet:              Pattern.TYPE__STRUCTURE__SET,
		Typenonfunction:               Pattern.TYPENONFUNCTION,
	},
	patterns: [
		{include: '#Block'},
		{include: '#Declaration'},
		{include: '#Statement'},
	],
}));
